version: '3'

#Declarar los servicios
#depends_on para ligar conexion entre contenedores
services:
  catclientes:
    container_name: apiclientes
    image: api_clientes
    build: .
    ports:
      - '1500:1500' 
    depends_on:
      - mongo
  mongo:
    container_name: mongoserver
    image: mongo
    ports:
      - '27017:27017'
  



